name: Publish RPM to the spec repo
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "IBM i build new release" ]
    branches: [ master ]
    types:
      - completed
      -
env:
  SPEC_REPO_SPEC_PATH: ${{ secrets.SPEC_REPO_SPEC_PATH }}
  SPEC_GITHUB_BASE_URL: ${{ secrets.SPEC_GITHUB_BASE_URL }}
  SPEC_REPO_NAME: ${{ secrets.SPEC_REPO_NAME }}
  SPEC_REPO_OWNER: ${{ secrets.SPEC_REPO_OWNER }}
  SPEC_GITHUB_TOKEN: ${{ secrets.SPEC_GITHUB_TOKEN }}
  SPEC_PROJECT_NAME: ${{ secrets.SPEC_PROJECT_NAME }}
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install nox
        run: python -m pip install nox
      - name: Publish RPM to the spec repo
        run: |
          nox -s publish