name: Publish RPM to the spec repo
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "IBM i build new release" ]
    branches: [ master ]
    types:
      - completed
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install nox
        run: python -m pip install nox
      - name: Publish RPM to the spec repo
        run: |
          nox -s publish