name: PR Review

on:
  workflow_dispatch:

  pull_request:
    branches: ["master"]

jobs:
  lint-and-python-tests:
    name: Run Linter and Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install nox
        run: python -m pip install nox
      - name: Run Linter
        run: nox -s lint
      - name: Run Python Tests
        run: nox -s test

  bob-recursive-example:
    name: Build bob-recursive-example
    runs-on: ubuntu-latest
    environment: COMMON1
    steps:
      - name: Checkout ibmi-bob
        uses: actions/checkout@v4
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: |
          npm i -g @ibm/ibmi-ci
          npm i -g @ibm/sourceorbit
      - name: Deploy to IBM i
        run: | 
          ici \
            --cmd "echo Setting up bob..." \
            --cmd "mkdir -p './builds/github_ci/${GITHUB_SHA}/ibmi_bob'" \
            --rcwd "./builds/github_ci/${GITHUB_SHA}/ibmi_bob" \
            --push "." \
            --cmd "echo Building bob-recursive-example..." \
            --cmd "git clone https://github.com/IBM/bob-recursive-example.git ../bob-recursive-example"
            --rcwd "../bob-recursive-example" \
            --ignore --cl "CRTLIB $(so -bl ${GITHUB_HEAD_REF})" \
            --cmd "../ibmi_bob/bin/makei b -e lib1=$(so -bl ${GITHUB_HEAD_REF})" \
            --ignore --cl "CLTLIB $(so -bl ${GITHUB_HEAD_REF})" \
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }}
          IBMI_USER: ${{ secrets.IBMI_USER }}
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
          BOBPATH: